apiVersion: v1
kind: Secret
metadata:
  name: {{ include "discord-bot.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "discord-bot.labels" . | nindent 4 }}
type: Opaque
stringData:
  DISCORD_TOKEN: {{ .Values.bot.discordToken | quote }}
  {{- if .Values.bot.welcomeChannelId }}
  WELCOME_CHANNEL_ID: {{ .Values.bot.welcomeChannelId | quote }}
  {{- end }}
